### ISSUE TITLE
Xianyun and Gaming missing

### ISSUE THREAD

**Issue by seeeeew** [man90es/Genshin-Party-Builder#179]
[Xianyun](https://genshin-impact.fandom.com/wiki/Xianyun) and [Gaming](https://genshin-impact.fandom.com/wiki/Gaming) were released on 2024-01-31 but aren't available in the party builder yet.

**Comment by man90es** [comment]
Thanks for the reminder. I should be able to add them this week. Alternatively, you can speed up the process by making a PR in https://github.com/genshindev/api

**Comment by man90es** [comment]
Gaming and Xianyun have been added to the app. They should appear shortly or you can press Ctrl+F5 to refresh the page w/o keeping cache. Feel free to report any other issues you find!

**Comment by seeeeew** [comment]
Thanks! I considered making a PR there after you suggested it, but I didn't know where to get the data and didn't have time to investigate. Would I need to type it out manually from the game or is there some way to export it?

**Comment by man90es** [comment]
https://genshin.honeyhunterworld.com is a good, regularly updated source, but it requires manually copying data to a JSON. I was considering making a scraping script for it at some point but never got to it
